version: '2'

services:
  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:${IMAGE_TAG:-2.2.2}
    tty: true
    user: root
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=example02
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=SampleOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    working_dir: /opt/gopath/src/chaincode
    command: /bin/sh -c 'go build -o simpleChaincode . &&
      CORE_CHAINCODE_LOGLEVEL=debug CORE_PEER_TLS_ENABLED=false CORE_CHAINCODE_ID_NAME=mycc:1.0 ./simpleChaincode -peer.address peer:7052'
    volumes:
      - /var/run/:/host/var/run/
      - ../sampleconfig/msp:/etc/hyperledger/msp
      - ${CC_SRC_PATH}:/opt/gopath/src/chaincode
    depends_on:
      - orderer
      - peer