version: '2'

services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:${IMAGE_TAG:-2.2.2}
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=orderer.block
      - ORDERER_GENERAL_LOCALMSPID=SampleOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../sampleconfig/msp:/etc/hyperledger/msp
      - ../channel-artifacts/genesis.block:/etc/hyperledger/fabric/orderer.block
    ports:
      - 7050:7050
  peer:
    container_name: peer
    image: hyperledger/fabric-peer:${IMAGE_TAG:-2.2.2}
    environment:
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=SampleOrg
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=chaincode=debug
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
      - /var/run/:/host/var/run/
      - ../sampleconfig/msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer
      - couchdb

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:${IMAGE_TAG:-2.2.2}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=SampleOrg
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './scripts/script.sh && cd http-cli && go build -o cli . && ./cli'
    volumes:
      - /var/run/:/host/var/run/
      - ../sampleconfig/msp:/etc/hyperledger/msp
      - ../channel-artifacts:/opt/gopath/src/chaincodedev/channel-artifacts
      - ../scripts:/opt/gopath/src/chaincodedev/scripts
      - ../http-cli:/opt/gopath/src/chaincodedev/http-cli
      - ../sampleconfig/msp:/opt/gopath/src/chaincodedev/sampleconfig/msp
      - ${CC_SRC_PATH:-../.}:/opt/gopath/src/chaincodedev/chaincode
    ports:
      - 8080:8080
    depends_on:
      - peer
      - orderer

  couchdb:
    container_name: couchdb
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 5984:5984